### ISSUE TITLE
Middle Click doesn't close tab

### ISSUE THREAD

**Issue by strigona-worksight** [Lej77/tab-unloader-for-tree-style-tab#1]
I have disabled "Middle click to unload tab", yet TreeStyleTab is still reporting that "mouseup is canceled by other addons" (via the debug). After disabling Tab Unloader, middle click works as expected.

Let me know if I can provide any more information or try anything.

Oddly enough, double-middle-click does close the tabs, but I'm not entirely sure.

**Comment by Lej77** [comment]
There is another option with the header `Prevent tab close on middle click` that is probably the reason for this. Disable it and middle click should close tabs as expected.

**Comment by strigona-worksight** [comment]
Ok, now I feel stupid... Thanks for pointing that out. I was so focused on "Middle click to unload tabs" section that I didn't see it.
