### ISSUE TITLE
Tab reordering when tab hiding is on

### ISSUE THREAD

**Issue by Kenqr** [Lej77/tab-unloader-for-tree-style-tab#10]
There is a bug regarding tab reordering when tab hiding and show hidden tabs in sidebar are both on.

A
└C
R (unloaded)

C is a children tab, and R is an unloaded root tab which is the next tab of C. Other tabs are not shown in the above graph.
Normally, I can drag any tab and release it between C and R to reorder it as the next sibling of C or as the previous sibling of R.
However, if tab hiding is on, I can only release any tab as the next sibling of C, but not as the previous sibling of R.

This bug does not happen when tab hiding is off or when R is loaded.
It also happens when C is a root tab, but doesn't matter in this case since the next sibling of C and the previous sibling of R are the same thing.

**Comment by Lej77** [comment]
Do you have the option `Suppress special behavior in Tree Style Tab regarding hidden tabs` enabled? Not being able to move tabs to unloaded tabs is the reason I implemented it. 

Tree Style Tab detects if tabs have the `.discarded` class and prevents drag and drop to them. The above option tries to remove this class as a workaround for the problem. The `Show hidden tabs in Tree Style Tab's sidebar` option just overrides the CSS code to show the hidden tabs and doesn't change the classes on the tabs in the Tree Style Tab sidebar.

**Comment by Lej77** [comment]
I've tested it and you are right. Drag and drop doesn't work even with the `Suppress special behavior in Tree Style Tab regarding hidden tabs` option enabled. I'll try to look into this later but it would be better if we could add support for shown `hidden` tabs to Tree Style Tab itself.

**Comment by Lej77** [comment]
Since Tree Style Tab now supports showing hidden tabs inside its options page this should no longer be an issue. See issue #45 and this extension option page which has been updated with more information in version 6.17.
