### ISSUE TITLE
configurable keyboard shortcuts for switching to the next/previous loaded tab only

### ISSUE THREAD

**Issue by iroedius** [Lej77/tab-unloader-for-tree-style-tab#11]
Would it be possible to add configurable keyboard shortcuts for switching to the next/previous **loaded** tab? Currently the next tab is selected regardless if it's loaded or unloaded.
And maybe something similar for hidden tabs, allowing switching to the next/previous tab regardless if it's hidden or not. As far as I can see switching to the next hidden tab using keyboard is currently impossible.

**Comment by Lej77** [comment]
This should definitely be possible and I'll try to add this when I get the time.

**Comment by Lej77** [comment]
Version 6.0 of this extension includes support for this! In the options page under the `Keyboard shortcuts` section there are two new shortcuts: `Select previous loaded tab` and `Select next loaded tab`. They should do what you want if you are still interested. Note that if you click on the keyboard shortcuts' sections they have some individual settings that can be used to configure how they work.
