### ISSUE TITLE
Tab context menu items without grouping

### ISSUE THREAD

**Issue by wvxwxvw** [Lej77/tab-unloader-for-tree-style-tab#22]
Please add the option not to group the context menu items. If possible. In this case, the submenu only takes time in vain.

**Comment by Lej77** [comment]
This isn't allowed by the WebExtensions API, see the [`menus`](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/menus#Creating_menu_items) API reference at the end of the `Creating menu items`:
>If you have created more than one context menu item or more than one tools menu item, then the items will be placed in a submenu. The submenu's parent will be labeled with the name of the extension. For example, here's an extension called "Menu demo" that's added two context menu items:

**Comment by wvxwxvw** [comment]
Well, I can do without it.
