### ISSUE TITLE
Settings page

### ISSUE THREAD

**Issue by wvxwxvw** [Lej77/tab-unloader-for-tree-style-tab#23]
1. Green is too bright for a dark theme. I made for myself - 120, 82%, 13%
2. "Enable", "Disable" and "Reset" buttons. Can they also be painted somehow? How it's done in TST:
![2020 09 07_123436](https://user-images.githubusercontent.com/13194155/92373258-b9f28d00-f106-11ea-8505-b5845a610662.png)

**Comment by Lej77** [comment]
I made some changes that hopefully addresses this in v6.1 of this extension. You can take a look and see what you think.

**Comment by wvxwxvw** [comment]
Yes, you did very well. Thanks.
