### ISSUE TITLE
Options are clipped in about:config (Maybe conflict with user css)

### ISSUE THREAD

**Issue by mzso** [Lej77/tab-unloader-for-tree-style-tab#26]
Hi!

When changing options I found that some of them are clipped and only appear for a blink of an I while an option section is being collapsed. For some reason there's no vertical scrollbar (only a pointless, superfluous horizontal one), and I didn't find a way to open the settings in a tab like for many other WE addons. (including TST)
![kép](https://user-images.githubusercontent.com/4479090/101277810-44569580-37b7-11eb-92a4-a296ea6aa237.png)
Zooming can make the situation worse, and better to some degree, but I never see more of the reset button than a few pixels.
![kép](https://user-images.githubusercontent.com/4479090/101277835-7f58c900-37b7-11eb-8c3a-c3bfb791c037.png)

**Comment by Lej77** [comment]
Hmm, seems there was some layout issues when the page got too small. I made some changes that should hopefully fix them. I also added a link to open the options page in a separate tab similar to the one Tree Style Tab provides in its options page. These changes are included in version 6.2 of this extension which I just released.

**Comment by mzso** [comment]
It appears correctly now.
