### ISSUE TITLE
Add a note w.r.t. private window permissions?

### ISSUE THREAD

**Issue by glaebhoerl** [Lej77/tab-unloader-for-tree-style-tab#28]
I get great use out of this extension, thank you for making it!

I had just written out a whole report about how, weirdly, some (but only some!) things didn't work in private windows; while doing due diligence on this I accidentally discovered that the TST preferences page itself has a section for granting private window permissions to TST-based addons (separate from the Firefox permissions, which I did already have enabled). After checking those boxes the issue went away.

As it seems rather non-obvious that enabling Firefox's "Run in Private Windows" setting is insufficient, maybe it would be worthwhile to add a note about this to the description or the preferences page or something?

**Comment by Lej77** [comment]
Good to hear that the extension is working well for you! The configuration for private windows is definitively a bit hard to figure out. I wrote some code to open a popup window with some information if this extension is granted access to private windows while Tree Style Tab isn't sending us messages for private windows. This change is included in version 6.4 of the extension and hopefully it will prevent anyone else from having this issue.

**Comment by glaebhoerl** [comment]
Wonderful!
