### ISSUE TITLE
Causes TST scrollbar to disappear

### ISSUE THREAD

**Issue by h4-n1** [Lej77/tab-unloader-for-tree-style-tab#31]
With a large number of unloaded tabs, tab unloader will make the TST scrollbar disappear. This issue started yesterday for me, and until today I could still get the scrollbar back by opening a large number of empty tabs. Maybe the numbers of open tabs required to activate the scrollbar isn't counting unloaded tabs?

Tab unloader version 6.5
TST version 3.8.7
Firefox version 89.0.2 on Manjaro KDE

**Comment by Lej77** [comment]
I don't think your issue is caused by this addon since it only makes minimal style changes to the TST sidebar. I suppose if you have activated some of the more experimental features such as showing hidden tabs then that could cause your problem. You can check what style changes this addon applies in the addons options page under the `Custom Tree Style Tab Style` header.

If you have custom style rules for TST under the advanced section of its option page then that is more likely to be the cause of your issue. It could also just be a bug of TST itself related to unloaded tabs.

**Comment by h4-n1** [comment]
Thanks for responding so quickly. I tested it after clearing all TST configs (following [this](https://github.com/piroor/treestyletab/issues/2911#issuecomment-851983770)) and with no other TST extensions enabled - enabling tab unloader immediately caused the scrollbar to disappear. Do you think it could still be a configuration issue on my end? Or should I ask at the TST repo?

**Comment by Lej77** [comment]
You could try reseting this extensions settings (there is a button for it on the options page). You could also try disabling any custom style rules that this extension applies to TST by checking that the text box in the `Custom Tree Style Tab Style` section is empty. This should remove all reasons that this extensions might cause you issues.

Here is the reasons that I can think of that might cause this issue:
- You have activated this addons experimental show hidden tabs feature and TST doesn't count the shown hidden tabs.
  - This should be disabled by default (so resetting to default settings would be one way to disable it)
  - The header of the `Tab Hiding` section in the option page should be red (not green or yellow) when this is disabled.
- The default `dim unloaded tabs` style somehow causes an issue with the TST style rules.
  - I can't really imagine how thus causes an issue except for maybe a Firefox bug.
    - Or maybe just a TST bug related to applying custom style rules from other addons.
  - Its easy to check if this is dsiabled by checking the `Custom Tree Style Tab Style` section of the options page.

Except for those things this addon only really listens for click events on the TST sidebar and that shouldn't affect the sidebar style.

**Comment by h4-n1** [comment]
I did this:
1. Disabled the addon
2. Exported TST configuration
3. Cleared TST configuration
4. Re-imported TST configuration
5. Enabled addon

And now it works.

> - You have activated this addons experimental show hidden tabs feature and TST doesn't count the shown hidden tabs.
>   - This should be disabled by default (so resetting to default settings would be one way to disable it)
>   - The header of the Tab Hiding section in the option page should be red (not green or yellow) when this is disabled.

I think this was it. Thanks a lot for your help.

**Comment by Lej77** [comment]
I'm glad you found a solution!
