### ISSUE TITLE
Unload Other Tabs

### ISSUE THREAD

**Issue by not-holar** [Lej77/tab-unloader-for-tree-style-tab#34]
I wanted to move to this extension from the unmaintained "UnloadTabs" one, but one Feature I'm missing from that is a button to unload all (including pinned, if a setting is set) other tabs (in the current window) except for the one(-s) you opened the context menu on.

**Comment by Lej77** [comment]
Thank you for your suggestion! I have implemented this functionality and it is available in version `6.7` of the extension. So just update the addon (might be done automatically depending on when Firefox auto checks for updates) and then go to the addon's option page to manually enable the context menu item. Note that you can also re-order the context menu item by using drag-and-drop on the handles that are located at the very left of each context menu item title (on the options page).
