### ISSUE TITLE
[Help/Support] How to access to hidden tabs?

### ISSUE THREAD

**Issue by SHHSSH** [Lej77/tab-unloader-for-tree-style-tab#43]
I've finally after 15 minutes or so figured out how to actually hide the unloaded tabs in TST's sidebar now through TST's settings.
However, I can't figure out how to actually show them? Preferably efficiently with a hotkey, however if it's through an about:unloads type of browser config or another type of tab access page, that's suitable too.

Please help if you can @Lej77 
Thanks.

**Comment by SHHSSH** [comment]
I often found after years of using TST that ~250+ or so tabs(even if unloaded) begins to become a little performance heavy for my little ol' laptop. I'll upgrade to DDR5 and more RAM in years to come.

So this addon has become priceless for me and I'd only just spotted the hidden tabs feature recently.
I used to use Auto Tab Discard, I actually deferred from it to your add on for quite a while then felt as if perhaps your addon was creating performance issues, though I believe I've isolated it down to a few other things instead.

I then for quite sometime used this "Lightweight" New Tab Suspender - https://github.com/pradeep-mishra/tab_suspender_firefox
But there's no support to with the addon and I had to python script just to allow for me to setup a hotkey to access it efficiently so it was high time I returned to your addon.

Really appreciate any help you can provide.
Thanks.

**Comment by SHHSSH** [comment]
Temp workaround is to load the Tab Unloader Options in an independent window, then visually hide the window and occasionally just alt-tab to it and press space bar. For which I'm utilising a vertically listed window manager replacement instead of Alt-Tab, which itself is merely an AHK script that shows window titles & if I customise a window title I can easily access it via its first letter as the default access key in the Alt-Tab list.

I then use a program called OnTopReplica to mirror the options settings' window so I am aware of what state the Hide tickbox is in(this is generally obvious other than when you have too many tabs active). 

There's another program that I think is quite good though if people cbf with a script & that is Alt-Tab Terminator @ - https://www.ntwind.com/software/alttabter.html

I hope you potentially have a better solution than my craziness.
Thanks again!

**Comment by Lej77** [comment]
I think the situation regarding the hidden tabs feature has gotten slightly better in version 6.17 of the addon:
- The options page has been updated with more information about how to show hidden tabs in Tree Style Tab. (See #45 for more details.)
- There is now a keyboard shortcut to toggle the hiding of unloaded tabs.

So I am closing this issue. Feel free to re-open it if there is something more you feel should be done.

**Comment by SHHSSH** [comment]
@Lej77 Your latest implementation works well, cheers mate.

**EDIT** One major problem is that it doesn't keep folder structure and just places the unhidden tabs loosely at the bottom it seems.

Thank you for the effort, I will attempt to work around it best I can if you cannot potentially offer a solution in the future.

**EDIT2** This actually seems to be because of "Folders" that I use as hierarchical tab structuring/organisation techniques, I was incorrect and falsely claimed that it does not hold the structure by quickly briefing it.

**EDIT3** Nah I am certain it has temperamental malfunctions with trees that's for sure, occasionally it'll just totally not show a subset of tabs and they are only accessible via Ctrl/Ctrl+Shift+Tab then you gotta outdent or indent to have them visible again. So the way in which I am attempting to structure my new browsing is to essentially not even use sub-tabs/trees anymore and just have the tabs underneath a folder that doesn't get unloaded, so it's easy to just toggle hide unloaded tabs on and off with the new hotkey option.

![capture_015_27072024_132703](https://github.com/user-attachments/assets/3422b41f-3389-4427-84ff-8049d91486aa)

Then you can just stick commonly used folders too for quick access, additionally I'd suggest to begin using a TST Scroll Tabs Up/Down by Page or Lines hotkey for quicker visibility of a large amount of tabs in one's sidebar. I used this hotkey seldomly in the past when I was able to folderise/tree all my tabs but now it's a definite necessity when working with a large amount in the sidebar vertically.
![capture_016_27072024_133018](https://github.com/user-attachments/assets/110aceba-8db1-4695-b4ce-83ac1d70d5ad)

P.S. The tree structure does work generally, just now that I began to run into the issue of some tabs disappearing sporadically I've just decided to not even worry with trees anymore for a while and give this a go over the next few months and see how I fend with it productively. 

Thanks again!
